version: "3"

##
# features to be added rabbitMq, multiple consumers etc
##
services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - '15672:15672'
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
  whatsapp:
    build: .
    depends_on:
      - rabbitmq
    volumes:
      - ./images:/data
    ports:
      - 5555:5555
    environment:
      - BROKER_URI=amqp://admin:mypass@rabbitmq:5672/%2F
      - ADMIN_URI=http://admin:mypass@rabbitmq:15672/api/
      - FLOWER_BASIC_AUTH=admin:changeit
      # - BACKEND_URI=amqp://admin:mypass@rabbitmq:5672/